#!/usr/bin/env python

import json

from bottle import ConfigDict
from playhouse.db_url import connect

from facehub.model import *


cfg = ConfigDict()
cfg.load_config("facehub.cfg")

db = connect(cfg['database.url'])
initDatabase(db)

with open('tests/fixtures/users.json', 'r') as f:
    users = json.loads(f.read())

def main(db, users):
    tables = db.get_tables()
    if 'users' in tables:
        db.drop_tables([User])

    db.create_tables([User])

    User.insert_many(users).execute()


if __name__ == '__main__':
    main(db, users)
